apiVersion: bedrockagentcorecontrol.services.k8s.aws/v1alpha1
kind: AgentRuntime
metadata:
  name: {{ .Values.agentName }}-{{ .Values.envName }}
  namespace: {{ .Values.agentName }}-{{ .Values.envName }}
spec:
  agentRuntimeArtifact:
    containerConfiguration:
      containerURI: {{ .Values.imageRepo }}/{{ .Values.agentName }}:{{ .Values.tag }}
  agentRuntimeName: {{ .Values.agentRuntimeName }}
  roleARN: {{ .Values.roleArn }}
  networkConfiguration:
    networkMode: PUBLIC
{{- if .Values.environmentVariables }}
  environmentVariables:
{{ toYaml .Values.environmentVariables | indent 4 }}
{{- end }}
