{{- if .Values.vaultSecrets.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .Values.vaultSecrets.secretName }}-ps
  namespace: {{ .Values.agentName }}
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: aws-secretsmanager
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ .Values.vaultSecrets.secretName }}
  data:
    - match:
        secretKey: {{ .Values.vaultSecrets.secretKey }}
        remoteRef:
          remoteKey: {{ .Values.vaultSecrets.secretKey }}
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          secretPushFormat: string
{{- end }}