apiVersion: v1
kind: ServiceAccount
metadata:
  name: cw-logs-tail
  namespace: {{ .Values.agentName }}-{{ .Values.envName }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.cloudWatchLogTailRoleArn }}